### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by dragnort1** [Chessnut/sample-schema#3]
Hi I just wanted to ask if, you have any basic schema's that have the base of nutscript that can be modified to create a schema different to other's in a way to make another gamemode. If so could I possibly get a link please?

**Comment by ghost** [comment]
You can use the Sample Schema Chessnut made, it's a really simple framework that's easy to work with. Is that what you mean't? Link to Sample: https://github.com/Chessnut/sample-schema

**Comment by ghost** [comment]
(Sorry if that's not what you mean't, I tend to go full retard from time to time)

**Comment by dragnort1** [comment]
How would I go around editing it?

**Comment by ghost** [comment]
Use notepad(++) to look at the codes for things like factions, hints aer inside to tell you what each one is for.

**Comment by dragnort1** [comment]
Alright, thanks.
